name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 18 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  static:
    name: static
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: windows, rust: stable-msvc}
          - {os: windows, rust: stable-gnu}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: {submodules: true}
      - name: Install Rust (${{matrix.rust}})
        uses: dtolnay/rust-toolchain@stable
        with: {toolchain: '${{matrix.rust}}'}
      - name: Build and test all crates
        run: cargo test --workspace -vvv --features hdf5-sys/deprecated,hdf5-sys/static,hdf5-sys/zlib --exclude hdf5-derive -j 1
      - name: Build and test with filters
        run: cargo test --workspace -vvv --features hdf5-sys/deprecated,hdf5-sys/static,hdf5-sys/zlib,lzf,blosc --exclude hdf5-derive
        if: matrix.rust != 'stable-gnu'
      - name: Run examples
        run: |
          cargo r -vvv --example simple --features hdf5-sys/deprecated,hdf5-sys/static,hdf5-sys/zlib,lzf,blosc
          cargo r -vvv --example chunking --features hdf5-sys/deprecated,hdf5-sys/static,hdf5-sys/zlib,lzf,blosc
        if: matrix.rust != 'stable-gnu'
